Switch to variable expasion for joining strings, better exit code
Switch to variable expansion when joining to a string, old way: "$var""string", new way" "${var}string". Looks a lot better in my opinion. Change the clean function to also handle exiting as well.

diff --git a/update-youtube-dl b/update-youtube-dl
--- a/update-youtube-dl
+++ b/update-youtube-dl
@@ -7,23 +7,28 @@ set -e
 # do we have the commands we need
 for i in wget grep chmod rm mktemp; do
 	if [ -z "`command -v $i`" ]; then
-		echo "Command $i not availabled, exiting with status 1"
+		echo "Command ${i} not availabled, exiting with status 1"
 		exit 1
 	fi
 done
 
 
 # we need a directory in tmp to work with
-tmp_dir="`mktemp -d`""/"
+tmp_dir="`mktemp -d`/"
 if [ ! -d "$tmp_dir" ]; then
-	echo "Failed to create $tmp_dir, exiting with status 1"
+	echo "Failed to create ${tmp_dir}, exiting with status 1"
 	exit 1
 fi
 
 
-clean_up() {
+clean_exit() {
 	if [ -d "$tmp_dir" ]; then
 		rm -r "$tmp_dir"
+	fi
+	if [ -z "$1" ]; then
+		exit 1
+	else
+		exit "$1"
 	fi
 }
 
@@ -31,8 +36,7 @@ clean_up() {
 # we need a local bin to move to
 if [ ! -d "/usr/local/bin/" ]; then
 	echo "Why don't you have a /usr/local/bin/?, exiting with status 1"
-	clean_up
-	exit 1
+	clean_exit 1
 fi
 
 
@@ -51,53 +55,49 @@ fi
 
 # fetch the sha so we can check the the version
 wget -q -4 "https://yt-dl.org/downloads/latest/SHA2-512SUMS" \
--O "$tmp_dir""sha2-512sums"
+-O "${tmp_dir}sha2-512sums"
 if [ "$?" != "0" ]; then
 	echo "Couldn't fetch sha2-512sums, exiting with status 1"
-	clean_up
-	exit 1
+	clean_exit 1
 fi
 
 
 # compare the current version with the next
 if [ "$current_version" != "NULL" ]; then
 	remote_version="`grep -o -E '[0-9]{4}\.[0-9]{2}\.[0-9]{2}' \
-		       "$tmp_dir""sha2-512sums"`"
+		       "${tmp_dir}sha2-512sums"`"
 	if [ -z "$remote_version" ]; then
 		echo "Couldn't get remote version, exiting with status 1"
-		clean_up
-		exit 1
+		clean_exit 1
 	fi
 	if [ "$current_version" = "$remote_version" ]; then
 		# we're up to date exit cleanly
-		clean_up
-		exit 0
+		clean_exit 0
 	fi
 fi
 
 
 # fetch the files we need
 wget -q -4 "https://yt-dl.org/downloads/latest/youtube-dl" \
--O "$tmp_dir""youtube-dl"
+-O "${tmp_dir}youtube-dl"
 if [ "$?" != "0" ]; then
 	echo "Couldn't fetch youtube-dl, exiting with status 1"
-	clean_up
-	exit 1
+	clean_exit 1
 fi
 
 
 # sha has to match
-if [ "`grep -q -i sha512sum "$tmp_dir""youtube-dl" \
-   | awk '{print $1}' "$tmp_dir""sha2-512sums"`" ]; then
+if [ "`grep -q -i sha512sum "${tmp_dir}youtube-dl" \
+   | awk '{print $1}' "${tmp_dir}sha2-512sums"`" ]; then
 	# move our file and chmod it
-	mv "$tmp_dir""youtube-dl" "/usr/local/bin/youtube-dl"
+	mv "${tmp_dir}youtube-dl" "/usr/local/bin/youtube-dl"
 	chmod +x "/usr/local/bin/youtube-dl"
 	if [ "$current_version" = "NULL" ]; then
-		echo "youtube-dl version $remote_version installed"
+		echo "youtube-dl version ${remote_version} installed"
 	else
-		echo "youtube-dl updated from version $current_version to $remote_version"
+		echo "youtube-dl updated from version ${current_version} to ${remote_version}"
 	fi
 fi
 
 
-clean_up
+clean_exit 0
