Temporary directory changes
Change the directory we use from /tmp/youtube-dl /tmp/youtube-dl-cron/. Also add a nanosecond time stamp to it to avoid conflicts.

diff --git a/update-youtube-dl b/update-youtube-dl
--- a/update-youtube-dl
+++ b/update-youtube-dl
@@ -4,13 +4,6 @@
 set -e
 
 
-clean_up() {
-	if [ -d "/tmp/youtube-dl/" ]; then
-		rm -r "/tmp/youtube-dl/"
-	fi
-}
-
-
 # do we have the commands we need
 for i in wget grep chmod rm; do
 	if [ -z "`command -v $i`" ]; then
@@ -21,11 +14,23 @@ done
 
 
 # we need a directory in tmp to work with
-mkdir "/tmp/youtube-dl/"
-if [ ! -d "/tmp/youtube-dl/" ]; then
-	echo "Failed to create /tmp/youtube-dl, exiting with status 1"
+tmp_dir="/tmp/youtube-dl-cron-""`date +'%N'`""/"
+if [ "$?" != "0"]; then
+	echo "Failed to get nanoseconds with date. exiting with status 1"
 	exit 1
 fi
+mkdir "$tmp_dir"
+if [ ! -d "$tmp_dir" ]; then
+	echo "Failed to create /tmp/youtube-dl-cron/, exiting with status 1"
+	exit 1
+fi
+
+
+clean_up() {
+	if [ -d "$tmp_dir" ]; then
+		rm -r "$tmp_dir"
+	fi
+}
 
 
 # we need a local bin to move to
@@ -51,7 +56,7 @@ fi
 
 # fetch the sha so we can check the the version
 wget -q -4 "https://yt-dl.org/downloads/latest/SHA2-512SUMS" \
--O "/tmp/youtube-dl/sha2-512sums"
+-O "$tmp_dir""sha2-512sums"
 if [ "$?" != "0" ]; then
 	echo "Couldn't fetch sha2-512sums, exiting with status 1"
 	clean_up
@@ -62,7 +67,7 @@ fi
 # compare the current version with the next
 if [ "$current_version" != "NULL" ]; then
 	remote_version="`grep -o -E '[0-9]{4}\.[0-9]{2}\.[0-9]{2}' \
-		       "/tmp/youtube-dl/sha2-512sums"`"
+		       "$tmp_dir""sha2-512sums"`"
 	if [ -z "$remote_version" ]; then
 		echo "Couldn't get remote version, exiting with status 1"
 		clean_up
@@ -78,7 +83,7 @@ fi
 
 # fetch the files we need
 wget -q -4 "https://yt-dl.org/downloads/latest/youtube-dl" \
--O "/tmp/youtube-dl/youtube-dl"
+-O "$tmp_dir""youtube-dl"
 if [ "$?" != "0" ]; then
 	echo "Couldn't fetch youtube-dl, exiting with status 1"
 	clean_up
@@ -87,10 +92,10 @@ fi
 
 
 # sha has to match
-if [ "`grep -q -i sha512sum /tmp/youtube-dl/youtube-dl \
-   | awk '{print $1}' "/tmp/youtube-dl/sha2-512sums"`" ]; then
+if [ "`grep -q -i sha512sum "$tmp_dir""youtube-dl" \
+   | awk '{print $1}' "$tmp_dir""sha2-512sums"`" ]; then
 	# move our file and chmod it
-	mv "/tmp/youtube-dl/youtube-dl" "/usr/local/bin/youtube-dl"
+	mv "$tmp_dir""youtube-dl" "/usr/local/bin/youtube-dl"
 	chmod +x "/usr/local/bin/youtube-dl"
 	if [ "$current_version" == "NULL" ]; then
 		echo "youtube-dl version $remote_version installed"
